title: my coding
author: my Git
email: your-ifefasina@gmail.com
description: > # this then means to ignore newlines until "baseurl:"
  Write an awesome description for your new site
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username:https://mobile.twitter.com/ifefas# DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/ifelajulo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to  r false to remove excerpts on the homepage
