title: my coding
author: my Git
email: your-ifefasina@gmail.com
description: > # this then means to ignore newlines until "baseurl:"
   Better site description.

# social links
twitter_username:https://mobile.twitter.com/ifefas# DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/ifelajulo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to  r false to remove excerpts on the homepage
